// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDictionary.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebDictionaryContext))]
    partial class WebDictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Dictionary", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DictionaryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DictionaryId");

                    b.ToTable("Dictionary");

                    b.HasData(
                        new
                        {
                            DictionaryId = 1,
                            Description = "Animals",
                            Name = "Animals"
                        },
                        new
                        {
                            DictionaryId = 2,
                            Description = "Days",
                            Name = "Days"
                        },
                        new
                        {
                            DictionaryId = 3,
                            Description = "Food",
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Phrase", b =>
                {
                    b.Property<int>("PhraseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhraseId"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DictionaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("EnPhrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UaPhrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhraseId");

                    b.HasIndex("DictionaryId");

                    b.ToTable("Phrase");

                    b.HasData(
                        new
                        {
                            PhraseId = 1,
                            Definition = "Animal Phrase Description",
                            DictionaryId = 1,
                            EnPhrase = "Mantis Shrimp",
                            UaPhrase = "Креветка богомол"
                        },
                        new
                        {
                            PhraseId = 2,
                            Definition = "Animal Phrase Description",
                            DictionaryId = 1,
                            EnPhrase = "Wolf Fish",
                            UaPhrase = "Риба Вовк"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DictionaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("EnWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UaWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.HasIndex("DictionaryId");

                    b.ToTable("Word");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Definition = "Animal Description",
                            DictionaryId = 1,
                            EnWord = "Cat",
                            UaWord = "Кіт"
                        },
                        new
                        {
                            WordId = 2,
                            Definition = "Animal Description",
                            DictionaryId = 1,
                            EnWord = "Dog",
                            UaWord = "Собака"
                        },
                        new
                        {
                            WordId = 3,
                            Definition = "Animal Description",
                            DictionaryId = 1,
                            EnWord = "Pig",
                            UaWord = "Свиня"
                        },
                        new
                        {
                            WordId = 4,
                            Definition = "Animal Description",
                            DictionaryId = 1,
                            EnWord = "Mouse",
                            UaWord = "Миша"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Phrase", b =>
                {
                    b.HasOne("Domain.Entities.Dictionary", "Dictionary")
                        .WithMany("Phrases")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Word", b =>
                {
                    b.HasOne("Domain.Entities.Dictionary", "Dictionary")
                        .WithMany("Words")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Dictionary", b =>
                {
                    b.Navigation("Phrases");

                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
